### PR TITLE
Added Apply Limit After Days option

### PR DESCRIPTION
**Pull request by ben-wckdrzr**
This seems like the best way to implement this option, will leave all versions within the days-to-keep range, and keep the limited number of versions from before that.

Let me know if you think it should be different.

All tested and working for me.

- - -
This change is [Reviewable](https://reviewable.io/reviews/reviewable/appengine-remove-action/6)

### CODE REVIEW

**Comment by pkaminski** [comment]
Thanks -- I'll take a look in a few days when I get back home.

**Review by pkaminski — COMMENTED** [review]
Thanks for working on this!  I like it overall, though I think it would be better if the versions within the days-to-keep range were included in the limit count.  Or to put it another way, `limit` picks from all versions to determine which ones to delete, but `days-to-keep` can exempt some of them from deletion if they're too recent.  I think these are cleaner semantics -- do you agree?

If so, you'd need a different approach:  instead of `--filter`, you'd probably need to change the format to output the creation date along with the ID, then post-filter the sliced list to exclude any entries that fall within `days-to-keep`.

Let me know what you think.

> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/reviewable/appengine-remove-action/6#-:-N9FgLRs22M3MSLzRFft:b-l3ghqw)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @ben-wckdrzr)

**Comment by ben-wckdrzr** [comment]
Hi, thanks for the review

I’m not sure I agree having the limit with the days_to_keep is right, although it probably does read better.

I see the main use-case for this is when I have a flurry of changes on one day (more than the limit), but then decide I wan’t to quickly get back to yesterday, or earlier.  In this use case we are likely exempting all versions beyond the limit.

That said, I feel like I wanted it as you say, until I realised this implementation was significantly simpler, although I’m now not convinced of the benefit of a more complex approach…

To my mind, this is a good first version approach, that could be build upon in a later version.

Potentially a better name than ‘days_to_keep’ would make all the above clearer??

Ben

**Review by pkaminski — COMMENTED** [review]
Yeah, fair enough -- the semantics aren't ideal, but a simpler implementation balances that out.  How about `apply_limit_after_days` for the parameter name instead?  It's longer but more explicit.

> *[Reviewable](https://reviewable.io/reviews/reviewable/appengine-remove-action/6#-:-N9YM-ym3nRTBoL3MV8C:b-tekvrh)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @ben-wckdrzr)

**Comment by ben-wckdrzr** [comment]
Sounds good - updated and tested 👍

**Review by pkaminski — COMMENTED** [review]
Looks good -- thanks!  I'll merge and cut a new release.

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/reviewable/appengine-remove-action/6#-:-N9bXHAy5dfDnEgBucYT:b-jzvmj7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ben-wckdrzr)

**Comment by pkaminski** [comment]
v2.2.0 is out now -- sorry it took a while.

**Pull request merged**
